### ISSUE TITLE
gh-pages does not list the content of a directory

### ISSUE THREAD

**Issue by napulen** [DDMAL/CantusEditor#8]
The code of the CantusEditor relies on making ajax calls to fetch the list of files.

For example:
- GET `https://localhost/resources/mei/`
Which would give something like this:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /resources/mei/</title>
<body>
<h2>Directory listing for /resources/mei/</h2>
<hr>
<ul>
<li><a href="csg-0390_007.mei">csg-0390_007.mei</a>
<li><a href="csg-0390_008.mei">csg-0390_008.mei</a>
<li><a href="csg-0390_009.mei">csg-0390_009.mei</a>
<li><a href="csg-0390_010.mei">csg-0390_010.mei</a>
<li><a href="csg-0390_014.mei">csg-0390_014.mei</a>
<li><a href="csg-0390_015.mei">csg-0390_015.mei</a>
<li><a href="csg-0390_016.mei">csg-0390_016.mei</a>
<li><a href="README.md">README.md</a>
<li><a href="s.html">s.html</a>
</ul>
<hr>
</body>
</html>
```
 
This will not happen on gh-pages
- GET https://ddmal.github.io/CantusEditor/resources/mei/
Which throws the following error
![image](https://user-images.githubusercontent.com/7258463/42389669-736ba56c-8117-11e8-96db-85dd82f1d8b6.png)

Other people have similar problems: https://stackoverflow.com/questions/39048654/how-to-enable-directory-indexing-on-github-pages

One possible solution for this is adding `index` files to each folder in the website, that will give the script the information it needs to work the same way as in the development environment.

I am not convinced that is the *best* way to solve the problem, but it is the *easiest* way.

**Comment by fujinaga** [comment]
Just include index.html files.

Ich

**Comment by napulen** [comment]
It is done. Made a few scripts to auto-generate these indexes. It is working now.
